[package]
name = "rwasm"
version = "1.0.0"
authors = ["Jay Bosamiya <jaybosamiya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
color-eyre = "0.5.0"

# Speed up `backtrace` even on a debug build. Suggested by `color-eyre`.
[profile.dev.package.backtrace]
opt-level = 3